name: "Power-Monitor"
description: "My first Power-Monitor add-on!"
version: "0.1.0"
slug: "power_monitor"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
